[package]
name = "portal"
version = "0.3.0"
authors = ["Spectra010s"]
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0.228", features = ["derive"] }
bincode = "1.3.3"
